routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/u/courses/list/category', 'Participant\ParticipantController@listCategory')->name('participant.course.listCategory');
Route::get('/u/courses/{category}/list', 'Participant\ParticipantController@list')->name('participant.course.list');
Route::get('/u/courses/{classroom}', 'Participant\ParticipantController@detail')->name('participant.course.detail');
Route::get('/u/courses/sayCheese/{classroom}/cheers', 'Participant\ParticipantController@saycheese')->name('participant.course.saycheese');
Route::get('/u/{user}/courses/{classroom?}', 'Participant\ParticipantController@document')->name('participant.course.document');
Route::post('/u/courses/{classroom}/test/{test}/register', 'Participant\ParticipantController@register')->name('participant.test.register');
Route::get('/u/certificates', 'Participant\ParticipantController@certificates')->name('participant.course.certificates');
Route::get('/user/courses/{classroom}/test_user/{test_user?}/note/participant', 'Participant\ParticipantController@note')->name('participant.course.note');
Route::get('/user/courses/{classroom}/note/nofound', 'Participant\ParticipantController@noteNofound')->name('participant.course.note.nofound');
Route::get('/u/courses/{classroom}/test/{test_user}/result', 'Participant\ParticipantController@result')->name('participant.course.results');
Route::get('u/courses/{classroom}/encuesta/{test_user}','Participant\ParticipantController@encuesta')->name('users.encuesta');
Route::get('/u/courses', 'Participant\CourseController@index')->name('participant.course.index');
Route::get('/courses/detail/{classroom}', 'Participant\CourseController@getDetail')->name('course.detail');





Route::get('/u/courses/{classroom}/test/{test}', 'Participant\ParticipantController@test')->name('participant.course.test');

//
Route::get('/certificate', 'User\CertificateController@index')->name('users.certificate');
Route::get('/certificate/{inscription}', 'User\CertificateController@create')->name('users.certificate.inscriptions');

Auth::routes();
Route::post('/register/company', 'Contractor\RegisterController@store')->name('register.company');

Route::resource('participants','ParticipantController');
Route::get('participants/{user}/modify', 'ParticipantController@modify')->name('participants.modify');
Route::get('participants/{user}/profile', 'ParticipantController@profile')->name('participants.profile');
Route::put('participant/{user}', 'ParticipantController@actualize')->name('participants.actualize');
Route::post('participants/import-excel','ParticipantController@import')->name('participants.import');


Route::resource('facilitators','FacilitadorController');
Route::get('facilitators/{user}/modify', 'FacilitadorController@modify')->name('facilitators.modify');
Route::put('facilitator/{user}', 'FacilitadorController@actualize')->name('facilitators.actualize');
Route::resource('companies','CompanyController');


Route::resource('categories','CategoryController');

Route::get('courses/u', 'Courses\ParticipantsController@list')->name('courses.participant.list');
Route::get('courses/{classroom}/u/{user}', 'Courses\ParticipantsController@detail')->name('courses.participant.detail');
Route::get('courses/{classroom}/types/{type}/u', 'Courses\ParticipantsController@list_type')->name('courses.participant.type');
Route::get('courses/{classroom}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');
Route::resource('courses.contents','Courses\CourseContentController');
Route::get('courses/{course}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');

Route::resource('courses.types','Courses\CourseTypeController');
Route::resource('courses.types.contents','Courses\CourseTypeContentController');
Route::get('courses/contents/{media}/download','Courses\CourseTypeContentController@download_content')->name('contents.download');

//Route::get('courses/contents/{course}', 'Courses\ContentController@index')->name('courses.contents.index');
Route::resource('courses','CourseController');
Route::resource('courses.certificates','Courses\CourseCertificateController');


Route::get('classrooms/{classroom}/test/{key?}','Classroom\TestController@list')->name('classrooms.list');
Route::resource('classrooms.tests','Classroom\TestController');
Route::resource('classrooms','ClassroomController');
Route::get('classrooms/{classroom}/consolidated', 'Classroom\ClassroomConsolidatedController@consolidated')
    ->name('classrooms.Consolidated');
Route::resource('classrooms.meetings','Classroom\MeetingController');
Route::resource('classrooms.assistances','Classroom\ClassroomAssistanceController');
Route::post('classrooms/{classroom}/assistances/register',
    'Classroom\ClassroomAssistanceController@register')
    ->name('classrooms.assistances.register');

//asistances en facilitator

Route::get('bank/{course}','BankController@save')->name('banks.save');
Route::get('banks/{course?}/module{module?}','BankController@list')->name('banks.list');
Route::resource('banks','BankController');
Route::post('banks/import-excel/{course}','BankController@import')->name('banks.import');;



Route::resource('roles','RoleController');
Route::resource('types','TypeController');
Route::resource('certificates','CertificateController');
Route::resource('users','UserController');
Route::get('courses/{classroom}/test/{test}','Course\CourseTestController@test')->name('courses.test');
Route::get('courses/{classroom}/encuesta/{test_user}','Course\CourseTestController@encuesta')->name('tests.encuesta');
Route::post('courses/{classroom}/test/{test}/register','Course\CourseTestController@register')->name('courses.test.register');
Route::get('courses/{classroom}/test/{test_user}/result','Course\CourseTestController@result')->name('courses.test.result');
Route::get('courses/{classroom}/test/{test_user}/detail','Course\CourseTestController@detail')->name('courses.test.detail');
Route::resource('users.testusers','User\TestUserController');


Route::resource('inscriptions','InscriptionController');
Route::post('inscriptions/import-excel','InscriptionController@import')->name('inscriptions.import');
Route::get('inscriptions/{classroom}/register','InscriptionController@register')->name('inscriptions.register');
Route::post('inscriptions/{classroom}','InscriptionController@save')->name('inscriptions.save');
Route::get('inscriptions/{classroom}/detail','InscriptionController@detail')->name('inscriptions.detail');

Route::resource('classrooms.tests','Classroom\TestController');
Route::get('classrooms.tests/{classroom}/list','Classroom\TestController@list')->name('tests.list');
Route::resource('courses.certificates','Courses\CourseCertificateController');

Route::get('modules/{course}','ModuleController@index')->name('modules.index');
route::get('modules/{course}/create','ModuleController@create')->name('modules.create');
Route::get('module/{module?}/courses/{course?}','ModuleController@show')->name('modules.show');
route::get('modules/{module}/edit','ModuleController@edit')->name('modules.edit');
route::post('modules/{course}','ModuleController@store')->name('modules.store');
route::put('modules/{module}','ModuleController@update')->name('modules.update');
Route::delete('modules/{module}','ModuleController@destroy')->name('modules.destroy');

//videos


//Question
Route::resource('forums','ForumController');
Route::get('courses/{classroom}/videos','ClassroomController@updateTimeVideo')->name('video.time');
Route::get('courses/{classroom}/video','ClassroomController@updateTimeCourse')->name('courses.time');
Route::post('u/courses/video/save/{inscription}','ClassroomController@videoSave')->name('video.save');
//has video guia

Route::get('participants/has/videoGuia/{classroom}','ClassroomController@hasVideoGuia')->name('participants.video.guia');

app/Content.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Type;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;



/**
 * App\Content
 *
 * @property int $id
 * @property int $course_id
 * @property int $type_id
 * @property string $name
 * @property string $description
 * @property string $atachment
 * @property int $child
 * @property int|null $reply
 * @property int|null $order
 * @property string $state
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content active()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereAtachment($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereChild($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereCourseId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereName($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereOrder($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereReply($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereState($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereTypeId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Content whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Content extends Model implements HasMedia
{
    use HasMediaTrait;

    protected $table='contents';

    const ACTIVE = '1';
    const LOCKED = '0';

    protected $fillable = [
        'course_id',
        'type_id',
        'name',
        'description',
        'parent_id',
        'content_link',
        'reply',
        'order',
        'logo_mini_name',
        'logo_mine_type',
        'state',
    ];
    public function type() {
        return $this->belongsTo(Type::class);
    }
    public function course() {
        return $this->belongsTo(Course::class, 'course_id');
    }
    public function banks() {
        return $this->hasMany(bank::class,'id');
    }
    public function scopeActive($q)
    {
        return $q->where('state', Content::ACTIVE);
    }

    public function getActive() {
        return $this->active()->get();
    }

    public function isActive() {
        return $this->state = Content::ACTIVE;
    }

    public function scopeIsModule($q)
    {
        $type=Type::select('id')->where('name','=','Modulo')->first();

        return $q->where('type_id',$type->id);
    }

    public function scopeOnlyModules($q,$id)
    {
        $module=Content::where('course_id',$id)->first();

        return $q->where('course_id',$module->id);
    }

    public function scopeIsCourse($q,$id)
    {
        return $q->where('course_id',$id);
    }

    public function Eliminate($id)
    {
        Content::findOrFail($id)->update(['state'=> '0']);

        return $this->state = Content::LOCKED;
    }
    public function attachment() {
        if ($this->media->first()) {
            return $this->media->first()->getFullUrl();
        }
        return null;
    }
    public function ShowModule($module,$course)
    {

        if(!$course->id==null){
            dump(' vacio');

            return $this->$module=Content::select(['description','id'])->where('course_id',$course->id)->active();
        }else{
            dump('no vacio');
            return $this->$module;
        }
    }

}

app/Http/Controllers/ContentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\content;
use App\Http\Requests\CreateContentRequest;
use DB;

class ContentController extends Controller
{
    function __construct(){
        $this->middleware('permission:content-list');
        $this->middleware('permission:content-create',['only'=>['create','store']]);
        $this->middleware('permission:content-edit',['only'=>['edit','update']]);
        $this->middleware('permission:content-delete',['only'=>['destroy']]);
        }

        public function index()
        {
            $contents = Content::select('contents.title','contents.is_question','contents.is_correct','contents.name as name')
                        ->join('contents','contents.id','=','contents.content_id')
                        ->where('contents.state',1)
                        ->get();

            return view('contents.index', compact('contents'));
        }

        public function create(Content $contents)
        {
            $contents=Content::pluck('name','id');
            return view('contents.create',compact('contents','contents'));
        }

        public function store(CreateContentRequest $request)
        {
            $fields = $request->validated();
            $contents = Content::create($fields);
            $message = 'El banco de preguntas "'. $contents->title .' fue registrado correctamente';
            return redirect()->route('contents.index')->with('success', $message);

        }

        public function show($id)
        {
            $contents=Content::findOrFail($id);
            return view('contents.show',compact('contents'));
        }


        public function edit(Content $contents,$id)
        {
            $content=Content::pluck('name','id');
            $contents::findOrFail($id);
            return view('contents.edit', compact('contents','contents'));
        }


        public function update(CreateContentRequest $request, Content $contents)
        {

            $fields = $request->validated();
            $contents->update($fields);
            $message = 'El banco de preguntas "'. $contents->title .' fue actualizado correctamente';
            return redirect()->route('contents.index')->with('success', $message);
        }



}

app/Http/Controllers/Courses/ContentController.php
<?php

namespace App\Http\Controllers\Courses;

use App\Course;
use App\Http\Controllers\Controller;
use App\Type;
use Illuminate\Http\Request;

class ContentController extends Controller
{
    public function index(Course $course) {
        $types = Type::get();
        return view('courses.content', compact('course', 'types'));
    }
}

resources/views/content/create.blade.php
@extends('layouts.template')

@section('content')

    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-video icon-gradient bg-mean-fruit"></i>
                </div>
                <div>
                    Registrar {{ $type->name }}
                    <div class="page-title-subheading">
                    </div>
                </div>
            </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                    <a href="{{ route('courses.types.show', [$course->id, $type->id]) }}" class="btn-shadow btn btn-info">
                        <span class="btn-icon-wrapper pr-1 opacity-8">
                            <i class="fa fa-undo-alt"></i>
                        </span>
                        REGRESAR
                    </a>
                </div>
            </div>
        </div>
    </div>

    @include('layouts.message')

    <div class="main-card mb-3 card">
        <div class="card-header">
            Ingrese los datos del {{ $type->name }} / {{ $course->name }}
        </div>
        <div class="card-body">
            <form action="{{ route('courses.types.contents.store', [$course->id, $type->id] ) }}" method="POST" enctype="multipart/form-data" id="formGeneral">
                @include('content.partials._form', ['btnText' => 'Guardar'])
            </form>
        </div>
    </div>

@endsection
@section('js')
    <script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('description')
        $('input[type="file"]').change(function(e){
            let fileName = e.target.files[0].name;
            $('.custom-file-label').html(fileName);
        });
    </script>
@endsection

resources/views/content/index.blade.php
@extends('layouts.template')


@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-video icon-gradient bg-mean-fruit"></i>
                </div>
                <div>
                    {{ $type->name }}
                    <div class="page-title-subheading">
                        Lista
                    </div>
                </div>
            </div>
            @can('type-create')
                <div class="page-title-actions">
                    <div class="d-inline-block dropdown">
                        <a href="{{ route('courses.types.contents.create', [$course->id, $type->id]) }}" class="btn-shadow btn btn-info">
                            <span class="btn-icon-wrapper pr-1 opacity-8">
                                <i class="fa fa-plus"></i>
                            </span>
                            REGISTRAR {{ Str::upper($type->name) }}
                        </a>
                    </div>
                </div>
            @endcan

        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @include('layouts.message')
            <div class="main-card mb-3 card">
                <div class="card-header card-header-tab">
                    <div class="card-header-title text-capitalize">
                        <i class="header-icon fa fa-th-list fa-xs icon-gradient bg-primary"></i>
                        {{ $course->name }}
                    </div>
                    <div class="btn-actions-pane-right text-capitalize">
                        {{--<a href="{{ route('modules.show',array($course->contents[0]->id,$course->id)) }}"
                           class="btn-wide btn-outline-2x mr-md-2 btn btn-outline-focus btn-sm">
                            <i class="fas fa-external-link-alt"></i>
                            Ver
                        </a>--}}
                        @if(Auth::user()->hasRole('participante'))
                            <a href="{{ route('courses.participant.detail', [$classroom->id, Auth::id()]) }}" class="btn-wide btn-outline-2x mr-md-2 btn btn-outline-focus btn-sm">
                                <i class="fa fa-undo-alt"></i> REGRESAR
                            </a>
                        @else
                            <a href="{{ route('courses.types.index', $course->id) }}" class="btn-wide btn-outline-2x mr-md-2 btn btn-outline-focus btn-sm">
                                <i class="fa fa-undo-alt"></i> REGRESAR
                            </a>
                        @endif
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover data" id="data">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col" >#</th>
                                <th scope="col" >Nombre</th>
                                @if($type->id == '1')
                                    <th scope="col" >Orden</th>
                                @endif
                                <th scope="col" >Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($course->contents as $content)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                <td>{{ $content->name }}</td>
                                    @if($type->id == '1')
                                        <td>{{ $content->order }}</td>
                                    @endif
                                    <td style="white-space:nowrap;">
                                        @can('module-list')
                                            <a class="btn btn-sm btn-icon-only btn-outline-info"
                                            href="{{ route('modules.show',$content->id) }}"><i class="pe-7s-look btn-icon-wrapper"></i></a>
                                        @endcan
                                        @can('type-show')
                                            <a class="btn btn-sm btn-icon-only btn-outline-info"
                                               href="{{ route('courses.types.contents.show',[$course->id, $type->id, $content->id]) }}">
                                                <i class="pe-7s-look btn-icon-wrapper"></i>
                                            </a>
                                        @endcan
                                        @can('type-edit')
                                            <a class="btn btn-sm btn-icon-only btn-outline-warning"
                                               href="{{ route('courses.types.contents.edit',[$course->id, $type->id, $content->id]) }}">
                                                <i class="pe-7s-pen btn-icon-wrapper"></i>
                                            </a>
                                        @endcan
                                        @can('type-delete')
                                        {!! Form::open(['method' => 'DELETE','route' => ['courses.types.contents.destroy', [$course->id, $type->id, $content->id]],'style'=>'display:inline']) !!}
                                            {{ Form::button('<i class="pe-7s-trash btn-icon-wrapper"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon-only btn-outline-danger'] ) }}
                                        {!! Form::close() !!}
                                        @endcan

                                        @if($content->media->first())
                                            <a class="btn btn-sm btn-icon-only btn-outline-success"
                                               href="{{ route('contents.download',[$content->media->first()->id]) }}">
                                                <i class="fas fa-cloud-download-alt btn-icon-wrapper"></i> Descargar
                                            </a>
                                        @endif
                                        @if($content->content_link)
                                            {{--<a class="btn btn-sm btn-icon-only btn-outline-info"
                                               href="{{  }}" target="_blank">
                                                <i class="fas fa-file btn-icon-wrapper"></i>
                                            </a>--}}
                                            @if(Auth::user()->hasRole('participante'))
                                                <a class="btn btn-sm btn-icon-only btn-outline-info"
                                                   href="{{ route('courses.participant.play', [$classroom->id, $type->id, $content->id]) }}">
                                                    <i class="fas fa-play-circle btn-icon-wrapper"></i> Ver
                                                </a>
                                            @else
                                                <a class="btn btn-sm btn-icon-only btn-outline-info"
{{--                                                   href="{{ route('courses.types.contents.play', [$course->id, $type->id, $content->id]) }}"--}}
                                                >
                                                    <i class="fas fa-play-circle btn-icon-wrapper"></i>
                                                </a>
                                            @endif

                                        @endif
                                        @can('bank-list')
                                            <a class="btn btn-sm btn-icon-only btn-outline-warning"
                                            href="{{ route('banks.list',array($course->id, $content->id)) }}"><i class="fas fa-box-open btn-icon-wrapper"></i></a>
                                        @endcan
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7">
                                        <p class="text-center">No hay ninguna reunión disponible</p>
                                    </td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
@endsection

resources/views/content/show.blade.php
@extends('layouts.template')


@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-video icon-gradient bg-mean-fruit"></i>
                </div>
                <div>
                    Reuniones
                    <div class="page-title-subheading">
                    </div>
                </div>
            </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                    <a href="{{ route('classrooms.meetings.create', [$classroom]) }}" class="btn-shadow btn btn-info">
                        <span class="btn-icon-wrapper pr-1 opacity-8">
                            <i class="fa fa-plus"></i>
                        </span>
                        REGISTRAR REUNIÓN
                    </a>
                </div>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            @include('layouts.message')
            <div class="main-card mb-3 card">
                <div class="card-header card-header-tab">
                    <div class="card-header-title text-capitalize">
                        <i class="header-icon fa fa-th-list fa-xs icon-gradient bg-primary"></i>
                        {{ $classroom->name }} / {{ $classroom->start_datetime }} / {{ $classroom->end_datetime }}
                    </div>
                    <div class="btn-actions-pane-right text-capitalize">
                        <a href="{{ route('classrooms.index') }}" class="btn-wide btn-outline-2x mr-md-2 btn btn-outline-focus btn-sm"><i class="fa fa-undo-alt"></i> REGRESAR</a>
                    </div>
                </div>
                <div class="card-body">
                    <div class="table-responsive">
                        <table class="table table-hover data" id="data">
                            <thead class="thead-light">
                            <tr>
                                <th scope="col" >#</th>
                                <th scope="col" >Fecha</th>
                                <th scope="col" >Plataforma</th>
                                <th scope="col" >Código</th>
                                <th scope="col" >Clave</th>
                                <th scope="col" >Link</th>
                                <th scope="col" >Acciones</th>
                            </tr>
                            </thead>
                            <tbody>
                            @forelse($classroom->meetings as $meeting)
                                <tr>
                                    <th scope="row">{{ $loop->iteration }}</th>
                                    <td><span class="text-nowrap">{{ $meeting->meeting_date }}</span></td>
                                    <td>{{ $meeting->platform }}</td>
                                    <td><span class="text-nowrap">{{ $meeting->platform_id }}</span></td>
                                    <td>{{ $meeting->platform_password }}</td>
                                    <td>{{ $meeting->platform_url }}</td>
                                    <td style="white-space:nowrap;">
                                        <a class="btn btn-sm btn-icon-only btn-outline-info" href="{{ route('classrooms.meetings.show',[$classroom->id, $meeting->id]) }}"><i class="pe-7s-look btn-icon-wrapper"></i></a>
                                        <a class="btn btn-sm btn-icon-only btn-outline-warning" href="{{ route('classrooms.meetings.edit',[$classroom->id, $meeting->id]) }}"><i class="pe-7s-pen btn-icon-wrapper"></i></a>
                                        {!! Form::open(['method' => 'DELETE','route' => ['classrooms.meetings.destroy', [$classroom->id, $meeting->id]],'style'=>'display:inline']) !!}
                                        {{ Form::button('<i class="pe-7s-trash btn-icon-wrapper"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon-only btn-outline-danger'] ) }}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @empty
                                <tr>
                                    <td colspan="7">
                                        <p class="text-center">No hay ninguna reunión disponible</p>
                                    </td>
                                </tr>
                            @endforelse
                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>
    </div>

@endsection
@section('js')
    <script type="text/javascript">
        $(document).ready(function() {
            $('#data').DataTable({

            });
        });
    </script>
@endsection