routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/u/courses/list/category', 'Participant\ParticipantController@listCategory')->name('participant.course.listCategory');
Route::get('/u/courses/{category}/list', 'Participant\ParticipantController@list')->name('participant.course.list');
Route::get('/u/courses/{classroom}', 'Participant\ParticipantController@detail')->name('participant.course.detail');
Route::get('/u/courses/sayCheese/{classroom}/cheers', 'Participant\ParticipantController@saycheese')->name('participant.course.saycheese');
Route::get('/u/{user}/courses/{classroom?}', 'Participant\ParticipantController@document')->name('participant.course.document');
Route::post('/u/courses/{classroom}/test/{test}/register', 'Participant\ParticipantController@register')->name('participant.test.register');
Route::get('/u/certificates', 'Participant\ParticipantController@certificates')->name('participant.course.certificates');
Route::get('/user/courses/{classroom}/test_user/{test_user?}/note/participant', 'Participant\ParticipantController@note')->name('participant.course.note');
Route::get('/user/courses/{classroom}/note/nofound', 'Participant\ParticipantController@noteNofound')->name('participant.course.note.nofound');
Route::get('/u/courses/{classroom}/test/{test_user}/result', 'Participant\ParticipantController@result')->name('participant.course.results');
Route::get('u/courses/{classroom}/encuesta/{test_user}','Participant\ParticipantController@encuesta')->name('users.encuesta');
Route::get('/u/courses', 'Participant\CourseController@index')->name('participant.course.index');
Route::get('/courses/detail/{classroom}', 'Participant\CourseController@getDetail')->name('course.detail');





Route::get('/u/courses/{classroom}/test/{test}', 'Participant\ParticipantController@test')->name('participant.course.test');

//
Route::get('/certificate', 'User\CertificateController@index')->name('users.certificate');
Route::get('/certificate/{inscription}', 'User\CertificateController@create')->name('users.certificate.inscriptions');

Auth::routes();
Route::post('/register/company', 'Contractor\RegisterController@store')->name('register.company');

Route::resource('participants','ParticipantController');
Route::get('participants/{user}/modify', 'ParticipantController@modify')->name('participants.modify');
Route::get('participants/{user}/profile', 'ParticipantController@profile')->name('participants.profile');
Route::put('participant/{user}', 'ParticipantController@actualize')->name('participants.actualize');
Route::post('participants/import-excel','ParticipantController@import')->name('participants.import');


Route::resource('facilitators','FacilitadorController');
Route::get('facilitators/{user}/modify', 'FacilitadorController@modify')->name('facilitators.modify');
Route::put('facilitator/{user}', 'FacilitadorController@actualize')->name('facilitators.actualize');
Route::resource('companies','CompanyController');


Route::resource('categories','CategoryController');

Route::get('courses/u', 'Courses\ParticipantsController@list')->name('courses.participant.list');
Route::get('courses/{classroom}/u/{user}', 'Courses\ParticipantsController@detail')->name('courses.participant.detail');
Route::get('courses/{classroom}/types/{type}/u', 'Courses\ParticipantsController@list_type')->name('courses.participant.type');
Route::get('courses/{classroom}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');
Route::resource('courses.contents','Courses\CourseContentController');
Route::get('courses/{course}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');

Route::resource('courses.types','Courses\CourseTypeController');
Route::resource('courses.types.contents','Courses\CourseTypeContentController');
Route::get('courses/contents/{media}/download','Courses\CourseTypeContentController@download_content')->name('contents.download');

//Route::get('courses/contents/{course}', 'Courses\ContentController@index')->name('courses.contents.index');
Route::resource('courses','CourseController');
Route::resource('courses.certificates','Courses\CourseCertificateController');


Route::get('classrooms/{classroom}/test/{key?}','Classroom\TestController@list')->name('classrooms.list');
Route::resource('classrooms.tests','Classroom\TestController');
Route::resource('classrooms','ClassroomController');
Route::get('classrooms/{classroom}/consolidated', 'Classroom\ClassroomConsolidatedController@consolidated')
    ->name('classrooms.Consolidated');
Route::resource('classrooms.meetings','Classroom\MeetingController');
Route::resource('classrooms.assistances','Classroom\ClassroomAssistanceController');
Route::post('classrooms/{classroom}/assistances/register',
    'Classroom\ClassroomAssistanceController@register')
    ->name('classrooms.assistances.register');

//asistances en facilitator

Route::get('bank/{course}','BankController@save')->name('banks.save');
Route::get('banks/{course?}/module{module?}','BankController@list')->name('banks.list');
Route::resource('banks','BankController');
Route::post('banks/import-excel/{course}','BankController@import')->name('banks.import');;



Route::resource('roles','RoleController');
Route::resource('types','TypeController');
Route::resource('certificates','CertificateController');
Route::resource('users','UserController');
Route::get('courses/{classroom}/test/{test}','Course\CourseTestController@test')->name('courses.test');
Route::get('courses/{classroom}/encuesta/{test_user}','Course\CourseTestController@encuesta')->name('tests.encuesta');
Route::post('courses/{classroom}/test/{test}/register','Course\CourseTestController@register')->name('courses.test.register');
Route::get('courses/{classroom}/test/{test_user}/result','Course\CourseTestController@result')->name('courses.test.result');
Route::get('courses/{classroom}/test/{test_user}/detail','Course\CourseTestController@detail')->name('courses.test.detail');
Route::resource('users.testusers','User\TestUserController');


Route::resource('inscriptions','InscriptionController');
Route::post('inscriptions/import-excel','InscriptionController@import')->name('inscriptions.import');
Route::get('inscriptions/{classroom}/register','InscriptionController@register')->name('inscriptions.register');
Route::post('inscriptions/{classroom}','InscriptionController@save')->name('inscriptions.save');
Route::get('inscriptions/{classroom}/detail','InscriptionController@detail')->name('inscriptions.detail');

Route::resource('classrooms.tests','Classroom\TestController');
Route::get('classrooms.tests/{classroom}/list','Classroom\TestController@list')->name('tests.list');
Route::resource('courses.certificates','Courses\CourseCertificateController');

Route::get('modules/{course}','ModuleController@index')->name('modules.index');
route::get('modules/{course}/create','ModuleController@create')->name('modules.create');
Route::get('module/{module?}/courses/{course?}','ModuleController@show')->name('modules.show');
route::get('modules/{module}/edit','ModuleController@edit')->name('modules.edit');
route::post('modules/{course}','ModuleController@store')->name('modules.store');
route::put('modules/{module}','ModuleController@update')->name('modules.update');
Route::delete('modules/{module}','ModuleController@destroy')->name('modules.destroy');

//videos


//Question
Route::resource('forums','ForumController');
Route::get('courses/{classroom}/videos','ClassroomController@updateTimeVideo')->name('video.time');
Route::get('courses/{classroom}/video','ClassroomController@updateTimeCourse')->name('courses.time');
Route::post('u/courses/video/save/{inscription}','ClassroomController@videoSave')->name('video.save');
//has video guia

Route::get('participants/has/videoGuia/{classroom}','ClassroomController@hasVideoGuia')->name('participants.video.guia');

app/Forum.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

/**
 * App\Forum
 *
 * @property int $id
 * @property int $course_id
 * @property int $user_id
 * @property string $title
 * @property string $description
 * @property int $child
 * @property string $state
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum active()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereChild($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereCourseId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereDescription($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereState($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereUpdatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Forum whereUserId($value)
 * @mixin \Eloquent
 */
class Forum extends Model
{
    const ACTIVE= '1';
    const LOCKED = '0';
    const TEXT_ACTIVE = 'Respondido';
    const TEXT_LOCKED = 'Pendiente';

    protected $fillable=
    [
        'user_id','email','title'
    ];
    public function state($id)
    {
        if($id ==0)
        {
            return Forum::TEXT_ACTIVE;
        }else
        {
            return Forum::TEXT_LOCKED;
        }

    }
    public function count_coments($forum)
    {
        return $forum->where('parent_id',$forum->id)->count();

    }
    public function users(){
        return $this->belongsTo(User::class);
    }

    public function scopeActive($q)
    {
        return $q->where('state', Client::ACTIVE);
    }

    public function getActive() {
        return $this->active()->get();
    }

    public function isActive() {
        return $this->status = Client::ACTIVE;
    }
}

app/Http/Controllers/ForumController.php
<?php

namespace App\Http\Controllers;

use App\Forum;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\CreateForumRequest;

class ForumController extends Controller
{
    function __construct() {
        $this->middleware('auth');
        $this->middleware('permission:forum-list');
        $this->middleware('permission:forum-create',['only'=>['create','store']]);
        $this->middleware('permission:forum-edit',['only'=>['edit','update']]);
        $this->middleware('permission:forum-delete',['only'=>['destroy']]);
    }

    public function index()
    {

        $user=Auth::user();
        $forums= Forum::where('parent_id',0)->with('users')->get();

        return view('forums.index',compact('forums'));
    }


    public function create(Forum $forum)
    {
        $user = Auth::user();

        return view('forums.create',compact('user','forum'));
    }


    public function store(CreateForumRequest $request, Forum $forum)
    {
        $user=Auth::user();
        $fields=$request->validated();
        $fields['user_id'] = $user->id;

        $forum::create($fields);

        $message = 'El foro del participante"'. $user->full_name .'"fue registrado correctamente';
        return redirect()->route('forums.index')->with('success', $message);
    }


    public function show(Forum $forum)
    {
        $user = Auth::user();

        return view('forums.show',compact('user','forum'));
    }


    public function edit($id)
    {
        //
    }


    public function update(Request $request, $id)
    {
        //
    }


    public function destroy($id)
    {
        //
    }
}

resources/views/forums/create.blade.php
@extends('layouts.template')


@section('content')

<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-home icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>CREAR FORO
                <div class="page-title-subheading">Ingrese su Pregunta
                </div>
            </div>
        </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                <a href="{{route('forums.index')}}"  class="btn-shadow btn btn-info">
                <span class="btn-icon-wrapper pr-1 opacity-8">
                    <i class="fa fa-plus"></i>
                </span>
                        Regresar
                    </a>
                </div>
            </div>
    </div>
</div>


    @include('layouts.message')

    <div class="main-card mb-3 card">
        <div class="card-body">
            <h5 class="card-title">Registre su Pregunta</h5>
            <form action="{{ route('forums.store') }}"
                method="POST" id="form_forums"
                enctype="multipart/form-data">
                @include('forums.partials.form', ['btnText' => 'Guardar'])
            </form>
        </div>
    </div>

@endsection
@section('js')
    <script src="{{ asset('vendor/ckeditor/ckeditor.js') }}"></script>
    <script>
        CKEDITOR.replace('description')
        $(document).ready(function () {
            $('#form_forums').submit(function()
            {
                $('.btnSubmit').prop('disabled',true);
                $('.btnSubmit').html('<p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i><span class="sr-only"></span> Registrando...</p>');
            });
        });
    </script>
@endsection

resources/views/forums/index.blade.php
@extends('layouts.template')


@section('content')
<link rel="stylesheet" href="{{ asset('complements/forums.css') }}">

@include('layouts.title', array(
            'icon'          => 'home',
            'title'         => 'Preguntas y Respuestas',
            'description'   => '',
            'button'           => 'registrar',
            'href'          => 'forums.create'))


<div class="row">
    <div class="col-md-12">
        <div class="main-card mb-3 card">

            <div class="card-body">
                <div class="table-responsive">
                    @include('layouts.message')
                </table>
                <h2 class="h4 category mb-0 p-2 rounded-top text-light">Foros</h2>
                <table class="align-middle table table-sm table-hover">
                    <thead class="thead-light">
                    <tr>
                        <th>#</th>
                        <th width="40%">Pregunta</th>
                        <th >Comentarios</th>
                        <th>Estado</th>
                        <th>Acciones</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($forums as $forum)
                    <tr>
                        <td>{{$loop->iteration}}</td>
                        <td>{{$forum->title}}</td>
                        <td>{{$forum->count_coments($forum)}}</td>
                        <td><span class="badge badge-success">{{$forum->state($forum->id)}}</span></td>
                        <td style="white-space:nowrap;">
                            @can('forum-list')
                            <a class="btn btn-sm btn-icon-only btn-outline-info"
                                href="{{route('forums.show',$forum->id)}}">
                                <i class="pe-7s-look btn-icon-wrapper"></i>
                            </a>
                            @endcan
                            @can('forum-edit')
                            <a class="btn btn-sm btn-icon-only btn-outline-warning"
                                href="#">
                                <i class="pe-7s-pen btn-icon-wrapper"></i>
                            </a>
                            @endcan
                            @can('forum-delete')
                            {!! Form::open(['method' => 'DELETE','route' => ['forums.destroy',$forum->id],'style'=>'display:inline']) !!}
                                    {{ Form::button('<i class="pe-7s-trash btn-icon-wrapper"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon-only btn-outline-danger'] ) }}
                            {!! Form::close() !!}
                            @endcan

                        </td>
                    </tr>
                    @endforeach
                </tbody>
            </table>

    <!--end of Aside Section-->
    <!--Footer-->
    <footer class="small bg-info">
        <div class="container">
        <ul class="list-inline mb-0">
            <li class="list-inline-item text-light">&copy; 2020 Inveritas Global Holdings Peru SA</li>
            <li class="list-inline-item"><a href="#" class="text-light">Privacy Policy</a></li>
            </ul>
        </div>
    </footer>
        </div>
        </div>
    </div>
    </div>
</div>



    @endsection

    @section('js')

    @endsection

resources/views/forums/show.blade.php
@extends('layouts.template')


@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-home icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>FORO
                <div class="page-title-subheading">Vista de Foro
                </div>
            </div>
        </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                <a href="{{route('forums.index')}}"  class="btn-shadow btn btn-info">
                <span class="btn-icon-wrapper pr-1 opacity-8">
                    <i class="fa fa-plus"></i>
                </span>
                        Regresar
                    </a>
                </div>
            </div>
    </div>
</div>


<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-header">
            <div class="media flex-wrap w-100 align-items-center"> <img style="width:45px;height:45px;" src="{{!(Auth::user()->avatar() === NULL) ? Auth::user()->avatar() : asset('img/image.png')}}" class="d-block ui-w-40 rounded-circle" alt="">
                    <div class="media-body ml-3"> <a href="javascript:void(0)" data-abc="true">{{$user->fullname}}</a>
                        <div class="text-muted small">0 days ago</div>
                    </div>
                    <div class="text-muted small ml-3">
                        <div><strong>0</strong> posts</div>
                    </div>
                </div>
            </div>
            <div class="card-body">
                <p>{{$forum->title}}</p>
            </div>
            <div class="card-footer d-flex flex-wrap justify-content-between align-items-center px-0 pt-0 pb-3">
                <div class="px-4 pt-3"><span class="text-muted d-inline-flex align-items-center align-middle ml-4"> <i class="fa fa-eye text-muted fsize-3"></i>&nbsp; <span class="align-middle">0</span> </span> </div>
                <div class="px-4 pt-3"> <button type="button" disabled class="btn btn-primary"><i class="ion ion-md-create"></i>&nbsp; Reply</button> </div>
            </div>
        </div>
    </div>
</div>

@endsection

@section('js')

@endsection