routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/u/courses/list/category', 'Participant\ParticipantController@listCategory')->name('participant.course.listCategory');
Route::get('/u/courses/{category}/list', 'Participant\ParticipantController@list')->name('participant.course.list');
Route::get('/u/courses/{classroom}', 'Participant\ParticipantController@detail')->name('participant.course.detail');
Route::get('/u/courses/sayCheese/{classroom}/cheers', 'Participant\ParticipantController@saycheese')->name('participant.course.saycheese');
Route::get('/u/{user}/courses/{classroom?}', 'Participant\ParticipantController@document')->name('participant.course.document');
Route::post('/u/courses/{classroom}/test/{test}/register', 'Participant\ParticipantController@register')->name('participant.test.register');
Route::get('/u/certificates', 'Participant\ParticipantController@certificates')->name('participant.course.certificates');
Route::get('/user/courses/{classroom}/test_user/{test_user?}/note/participant', 'Participant\ParticipantController@note')->name('participant.course.note');
Route::get('/user/courses/{classroom}/note/nofound', 'Participant\ParticipantController@noteNofound')->name('participant.course.note.nofound');
Route::get('/u/courses/{classroom}/test/{test_user}/result', 'Participant\ParticipantController@result')->name('participant.course.results');
Route::get('u/courses/{classroom}/encuesta/{test_user}','Participant\ParticipantController@encuesta')->name('users.encuesta');
Route::get('/u/courses', 'Participant\CourseController@index')->name('participant.course.index');
Route::get('/courses/detail/{classroom}', 'Participant\CourseController@getDetail')->name('course.detail');





Route::get('/u/courses/{classroom}/test/{test}', 'Participant\ParticipantController@test')->name('participant.course.test');

//
Route::get('/certificate', 'User\CertificateController@index')->name('users.certificate');
Route::get('/certificate/{inscription}', 'User\CertificateController@create')->name('users.certificate.inscriptions');

Auth::routes();
Route::post('/register/company', 'Contractor\RegisterController@store')->name('register.company');

Route::resource('participants','ParticipantController');
Route::get('participants/{user}/modify', 'ParticipantController@modify')->name('participants.modify');
Route::get('participants/{user}/profile', 'ParticipantController@profile')->name('participants.profile');
Route::put('participant/{user}', 'ParticipantController@actualize')->name('participants.actualize');
Route::post('participants/import-excel','ParticipantController@import')->name('participants.import');


Route::resource('facilitators','FacilitadorController');
Route::get('facilitators/{user}/modify', 'FacilitadorController@modify')->name('facilitators.modify');
Route::put('facilitator/{user}', 'FacilitadorController@actualize')->name('facilitators.actualize');
Route::resource('companies','CompanyController');


Route::resource('categories','CategoryController');

Route::get('courses/u', 'Courses\ParticipantsController@list')->name('courses.participant.list');
Route::get('courses/{classroom}/u/{user}', 'Courses\ParticipantsController@detail')->name('courses.participant.detail');
Route::get('courses/{classroom}/types/{type}/u', 'Courses\ParticipantsController@list_type')->name('courses.participant.type');
Route::get('courses/{classroom}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');
Route::resource('courses.contents','Courses\CourseContentController');
Route::get('courses/{course}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');

Route::resource('courses.types','Courses\CourseTypeController');
Route::resource('courses.types.contents','Courses\CourseTypeContentController');
Route::get('courses/contents/{media}/download','Courses\CourseTypeContentController@download_content')->name('contents.download');

//Route::get('courses/contents/{course}', 'Courses\ContentController@index')->name('courses.contents.index');
Route::resource('courses','CourseController');
Route::resource('courses.certificates','Courses\CourseCertificateController');


Route::get('classrooms/{classroom}/test/{key?}','Classroom\TestController@list')->name('classrooms.list');
Route::resource('classrooms.tests','Classroom\TestController');
Route::resource('classrooms','ClassroomController');
Route::get('classrooms/{classroom}/consolidated', 'Classroom\ClassroomConsolidatedController@consolidated')
    ->name('classrooms.Consolidated');
Route::resource('classrooms.meetings','Classroom\MeetingController');
Route::resource('classrooms.assistances','Classroom\ClassroomAssistanceController');
Route::post('classrooms/{classroom}/assistances/register',
    'Classroom\ClassroomAssistanceController@register')
    ->name('classrooms.assistances.register');

//asistances en facilitator

Route::get('bank/{course}','BankController@save')->name('banks.save');
Route::get('banks/{course?}/module{module?}','BankController@list')->name('banks.list');
Route::resource('banks','BankController');
Route::post('banks/import-excel/{course}','BankController@import')->name('banks.import');;



Route::resource('roles','RoleController');
Route::resource('types','TypeController');
Route::resource('certificates','CertificateController');
Route::resource('users','UserController');
Route::get('courses/{classroom}/test/{test}','Course\CourseTestController@test')->name('courses.test');
Route::get('courses/{classroom}/encuesta/{test_user}','Course\CourseTestController@encuesta')->name('tests.encuesta');
Route::post('courses/{classroom}/test/{test}/register','Course\CourseTestController@register')->name('courses.test.register');
Route::get('courses/{classroom}/test/{test_user}/result','Course\CourseTestController@result')->name('courses.test.result');
Route::get('courses/{classroom}/test/{test_user}/detail','Course\CourseTestController@detail')->name('courses.test.detail');
Route::resource('users.testusers','User\TestUserController');


Route::resource('inscriptions','InscriptionController');
Route::post('inscriptions/import-excel','InscriptionController@import')->name('inscriptions.import');
Route::get('inscriptions/{classroom}/register','InscriptionController@register')->name('inscriptions.register');
Route::post('inscriptions/{classroom}','InscriptionController@save')->name('inscriptions.save');
Route::get('inscriptions/{classroom}/detail','InscriptionController@detail')->name('inscriptions.detail');

Route::resource('classrooms.tests','Classroom\TestController');
Route::get('classrooms.tests/{classroom}/list','Classroom\TestController@list')->name('tests.list');
Route::resource('courses.certificates','Courses\CourseCertificateController');

Route::get('modules/{course}','ModuleController@index')->name('modules.index');
route::get('modules/{course}/create','ModuleController@create')->name('modules.create');
Route::get('module/{module?}/courses/{course?}','ModuleController@show')->name('modules.show');
route::get('modules/{module}/edit','ModuleController@edit')->name('modules.edit');
route::post('modules/{course}','ModuleController@store')->name('modules.store');
route::put('modules/{module}','ModuleController@update')->name('modules.update');
Route::delete('modules/{module}','ModuleController@destroy')->name('modules.destroy');

//videos


//Question
Route::resource('forums','ForumController');
Route::get('courses/{classroom}/videos','ClassroomController@updateTimeVideo')->name('video.time');
Route::get('courses/{classroom}/video','ClassroomController@updateTimeCourse')->name('courses.time');
Route::post('u/courses/video/save/{inscription}','ClassroomController@videoSave')->name('video.save');
//has video guia

Route::get('participants/has/videoGuia/{classroom}','ClassroomController@hasVideoGuia')->name('participants.video.guia');

app/Bank.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use App\Content;
use Illuminate\Support\Arr;


/**
 * App\Bank
 *
 * @property int $id
 * @property int $content_id
 * @property string $title
 * @property int $is_question
 * @property int $is_correct
 * @property int $child
 * @property string $state
 * @property \Illuminate\Support\Carbon|null $created_at
 * @property \Illuminate\Support\Carbon|null $updated_at
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank active()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank newModelQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank newQuery()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank query()
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereChild($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereContentId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereCreatedAt($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereId($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereIsCorrect($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereIsQuestion($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereState($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereTitle($value)
 * @method static \Illuminate\Database\Eloquent\Builder|\App\Bank whereUpdatedAt($value)
 * @mixin \Eloquent
 */
class Bank extends Model
{
    protected $fillable=[
    'content_id','title','is_question','is_correct','parent_id','state',
    ];
    const ACTIVE = '1';
    const LOCKED = '0';
    const PARENT_ID = null;

    public function content() {
        return $this->belongsTo(Content::class);
    }
    public function scopeActive($q)
    {
        return $q->where('state', Bank::ACTIVE);
    }

    public function scopeOnlyModules($q,$id)
    {
        return $q->join('contents','contents.id','=','banks.content_id')
        ->where('contents.course_id','=',$id);

    }
    public function scopeMyModule($q,$module)
    {
        if(!$module->id==null){

            return $q->where('content_id',$module->id);
        }else{
            return null;
        }
    }
    public function scopeOnlyQuestion($q)
    {
        return $q->where('banks.parent_id','=',null)
        ->orderby('banks.created_at');

    }
    public function CreateBank($request,$bank){


        $fields = $request->validated();
        //crear la pregunta
        $bank=Bank::create($request->except(['title2','is_correct']));


        foreach($fields['title2'] as $field){

                $fields=Arr::except($_POST, 'title2');
                $fields['title']=$field;
                $fields['parent_id']=$bank->id;
                $fields['is_question']=0;
        }
        foreach($fields['is_correct'] as $is_correct){
            $fields['is_correct']=$is_correct;
            $bank=Bank::create($fields);
        }
    }
    public function CreateOption($fields,Bank $bank){

        foreach($fields['is_correct'] as $field){
            $fields['is_correct']=$field;
        }

        foreach($fields['title'] as $field ){
            $fields['title']=$field;

            $bank::create($fields);
        }
    }
    public function parent()
    {
        return $this->belongsTo(Bank::class,'parent_id');
    }
    public function childs() {
        return $this->hasmany(Bank::class,'parent_id');
    }

    public function Eliminate($id)
    {
        $bank=Bank::findOrFail($id)->update(['state'=> '0']);

        return $this->state = Bank::LOCKED;
    }

    public function correctAnswer($id)
    {
        $child=Bank::where('id',$id)->first();

        $bank=Bank::where(['parent_id'=>$child->parent_id,'is_correct' => 1])->first();
        return $bank->title;

    }

    public function getActive() {
        return $this->active()->get();
    }

    public function isActive() {
        return $this->state = Bank::ACTIVE;
    }


}

app/Http/Controllers/BankController.php
<?php

namespace App\Http\Controllers;

use DB;
use App\Bank;
use App\Course;
use App\Content;
use App\Imports\BanksImport;
use Illuminate\Http\Request;
use Maatwebsite\Excel\Facades\Excel;
use App\Http\Requests\CreateBankRequest;
use Exception;

class BankController extends Controller
{
    function __construct(){
    $this->middleware('permission:bank-list');
    $this->middleware('permission:bank-create',['only'=>['create','store']]);
    $this->middleware('permission:bank-edit',['only'=>['edit','update']]);
    $this->middleware('permission:bank-delete',['only'=>['destroy']]);
    }
    public function index()
    {
    }
    public function list(Course $course, Content $module)
    {

        $banks = Bank::query()->select(['banks.id','banks.title','banks.content_id'])
                    ->with(['content'])
                    ->MyModule($module)
                    ->OnlyModules($course->id)//solo modulos que pertenecen el curso
                    ->where('banks.state','=',1)
                    ->OnlyQuestion()
                    ->get();

        return view('banks.index', compact('banks','course','module'));
    }
    public function save(Bank $bank, Course $course)
    {
        $contents=Content::OnlyModules($course->id)->pluck('name','id');

        return view('banks.questions.create',compact('bank','course','contents'));
    }


    public function store(CreateBankRequest $request,Bank $bank)
    {

        $bank->CreateBank($request,$bank);
        $message = 'El banco de preguntas "'. $bank->title .' fue registrado correctamente';
        return redirect()->route('banks.list',$request->course_id)->with('success', $message);

    }
    public function import(Request $request,Course $course)
    {
        ini_set('max_execution_time', 720000);
        ini_set('memory_limit', -1);

        $file= $request->file('file_up');
        try{
            Excel::import(new BanksImport($course), $file);

        }catch(Exception $e){
            return back()->with('error', $e->getMessage());
        }
        return back()->with('success', 'Se subio el banco de preguntas');
    }

    public function show($id)
    {
        $banks=Bank::findOrFail($id);
        return view('banks.show',compact('banks'));
    }


    public function edit(Bank $bank)
    {
        $contents=Content::pluck('name','id');

        return view('banks.edit', compact('bank','contents'));
    }
    public function destroy(Bank $bank)
    {
        $bank->Eliminate($bank->id);

        return redirect()->back()->with('danger','El Banco:  '.$bank->title .' en la fecha '. $bank->created_at .' fue Eliminado con exito');
    }


    public function update(CreateBankRequest $request, Bank $banks)
    {


        $fields = $request->validated();
        $banks->update($fields);
        $message = 'El banco de preguntas "'. $banks->title .' fue actualizado correctamente';
        return redirect()->route('banks.index')->with('success', $message);
    }

}

resources/views/banks/create.blade.php
@extends('layouts.template')


@section('content')

@include('layouts.title', array(
                                'icon'         =>'home',
                                'title'         => 'Registrar Banco',
                                'description'   => '',
                                'button'           => 'Regresar',
                                'href'          => 'banks.index'))

    
        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif

        {!! Form::open(array('route' => 'banks.store','files'=>true,'id'=>'formBanks','method'=> 'POST','class' => 'form-horizontal')) !!}
        @include('banks.partials.form', ['btnText' => 'Guardar'])
        {!! Form::close() !!}

@endsection
@section('js')

    <script>
        $(document).ready(function () {

            $('.selection-input').select2({
                theme: "bootstrap"
            });
            $('#formBanks').submit(function()
            {
                $('.btnSubmitCourse').prop('disabled',true);
                $('.btnSubmitCourse').html('<p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i><span class="sr-only"></span> Registrando...</p>');
            });
        });
    </script>
@endsection

resources/views/banks/edit.blade.php
@extends('layouts.template')


@section('content')

<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-home icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>BANCO
                <div class="page-title-subheading">Editar Banco
                </div>
            </div>
        </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                <a href="{{route('banks.list',$bank->content->course->id)}}"  class="btn-shadow btn btn-info">
                <span class="btn-icon-wrapper pr-1 opacity-8">
                    <i class="fa fa-plus"></i>
                </span>
                        Regresar
                    </a>
                </div>
            </div>
    </div>
</div>




        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif

        <form action="{{ route('banks.update',$bank->id) }}"
                method="POST" id="formbanks" class="form-horizontal">

        @include('banks.questions.partials.forms')
        </form>

@endsection

@section('js')

    <script>
        $(document).ready(function () {

            $('.selection-input').select2({
                theme: "bootstrap"
            });
            $('.btncontent').select2({
                width: '100%'
            });

            $('#formBanks').submit(function()
            {
                $('.btnSubmitCourse').prop('disabled',true);
                $('.btnSubmitCourse').html('<p><i class="fa fa-spinner fa-spin fa-2x fa-fw"></i><span class="sr-only"></span> Registrando...</p>');
            });
        });
    </script>
    <script>
    $('#save').click(function(){

        var count = 1;


        dynamic_field(count);

        function dynamic_field(number)
        {
        html = '<tr>';

            html += '<td><input type="text" name="title[]" value="{{ old('title', $bank->title) }}" placeholder="Ingrese una opcion"class="form-control" /></td>';
            html += '<td><input type="hidden" name="parent_id"  value="{{$bank->id}}"></td>';
            html += '<td><input type="hidden" name="course_id" class="form-control" value="{{$bank->content->course->id}}"></td>';
            html += '<td><label class="btn btn-success active"><input type="checkbox" name="is_correct[]"  value="1" {{ old('is_correct', $bank->is_correct) == '1' ? 'checked' : '' }} autocomplete="off" checked><span class="glyphicon glyphicon-ok"></span></label></td>';

            if(number > 1)
            {

                html += '<td><button type="button" name="remove" id="" class="btn btn-danger remove"><span class="btn-icon-wrapper pr-1 opacity-8"><i class="fa fa-minus"></i></span>Remover</button></td></tr>';
                $('#pocos').append(html);
                //$('tbody').append(html);
            }
            else
            {

                html += '<td><button type="button" name="add" id="add" class="btn btn-success"><span class="btn-icon-wrapper pr-1 opacity-8"><i class="fa fa-plus"></i></span>Añadir Opciones</button></td></tr>';

                $('#pocos').html(html);
                //$('tbody').html(html);
            }
        }

        $(document).on('click', '#add', function(){

        count++;
        dynamic_field(count);
        });



        $(document).on('click', '.remove', function(){
        count--;
        $(this).closest("tr").remove();
        });

        $('#formBanks').on('submit', function(event){
            event.preventDefault();
            $.ajax({
                url:'{{ route("banks.store",$bank->id) }}',
                method:'POST',
                data:$(this).serialize(),
                dataType:'json',
                beforeSend:function(){
                    $('#save').attr('disabled','disabled');
                },
                success:function(data)
                {
                    if(data.error)
                    {
                        var error_html = '';
                        for(var count = 0; count < data.error.length; count++)
                        {
                            error_html += '<p>'+data.error[count]+'</p>';
                        }
                        $('#result').html('<div class="alert alert-danger">'+error_html+'</div>');
                    }
                    else
                    {
                        dynamic_field(1);
                        $('#result').html('<div class="alert alert-success">'+data.success+'</div>');
                    }
                    $('#save').attr('disabled', false);
                }
            })
        });

        });
        </script>



@endsection

resources/views/banks/index.blade.php
@extends('layouts.template')


@section('content')

        <div class="app-page-title">
            <div class="page-title-wrapper">
                <div class="page-title-heading">
                    <div class="page-title-icon">
                        <i class="pe-7s-home icon-gradient bg-mean-fruit">
                        </i>
                    </div>
                    <div>Banco
                        <div class="page-title-subheading">Lista de Banco
                        </div>
                    </div>
                </div>
                    <div class="page-title-actions">
                        <div class="d-inline-block dropdown">
                        <a href="{{ route('banks.save',$course->id) }}" class="btn-shadow btn btn-info">
                        <span class="btn-icon-wrapper pr-1 opacity-8">
                            <i class="fa fa-plus"></i>
                        </span>
                                REGISTRAR BANCO
                            </a>
                        </div>


                    </div>
            </div>
        </div>

    @include('layouts.message')
    <div class="main-card mb-3 card">
        <div class="card-body">
    <div class="table-responsive">
    <table class="align-middle table table-sm table-hover" id="datatable">
        <thead class="thead-light">
            <tr>
                <th scope="col" >#</th>
                <th width="50%"scope="col" >Preguntas</th>
                <th scope="col" >Modulo</th>
                <th scope="col" >Acciones</th>

            </tr>
        </thead>
        <tbody>

            @foreach ($banks as $bank)
            <tr>
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{ $bank->title }}</td>
                <td>{{ $bank->content->name }}</td>

                <td style="white-space:nowrap;">
                                <a class="btn btn-sm btn-icon-only btn-outline-info" href="{{ route('banks.show',$bank->id) }}"><i class="pe-7s-look btn-icon-wrapper"></i></a>
                                <a class="btn btn-sm btn-icon-only btn-outline-warning" href="{{ route('banks.edit',$bank->id) }}"><i class="pe-7s-pen btn-icon-wrapper"></i></a>
                                {!! Form::open(['method' => 'DELETE','route' => ['banks.destroy', $bank->id],'style'=>'display:inline']) !!}
                                    {{ Form::button('<i class="pe-7s-trash btn-icon-wrapper"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon-only btn-outline-danger'] ) }}
                                {!! Form::close() !!}
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
</div>
</div>
</div>
    <p class="text-center text-primary"><small>Campus Virtual</small></p>
@endsection


@section('js')

@endsection

resources/views/banks/question.blade.php
@extends('layouts.template')


@section('content')
<div class="app-page-title">
    <div class="page-title-wrapper">
        <div class="page-title-heading">
            <div class="page-title-icon">
                <i class="pe-7s-home icon-gradient bg-mean-fruit">
                </i>
            </div>
            <div>Preguntas
                <div class="page-title-subheading">Lista de Preguntas
                </div>
            </div>
        </div>
            <div class="page-title-actions">
                <div class="d-inline-block dropdown">
                    <a href="#" data-toggle="modal" data-target="#Modal_create" class="btn-shadow btn btn-info">
                <span class="btn-icon-wrapper pr-1 opacity-8">
                    <i class="fa fa-plus"></i>
                </span>
                        Agregar
                    </a>
                </div>
            </div>
    </div>
</div>


        @if ($message = Session::get('success'))
            <div class="alert alert-success">
                <p>{{ $message }}</p>
            </div>
        @endif
        @if ($message = Session::get('fail'))
            <div class="alert alert-danger">
                <p>{{ $message }}</p>
            </div>
        @endif

    <div class="table-responsive">
    <table class="table table-hover table-bordered" id="datatable">
        <thead>
            <tr>
                <th scope="col" >#</th>
                <th scope="col" >Titulo</th>
                <th scope="col" >Preguntas</th>
                <th scope="col" >Acciones</th>

            </tr>
        </thead>
        <tbody>

            @foreach ($banks as $bank)
            <tr>
                <th scope="row">{{$loop->iteration}}</th>
                <td>{{ $bank->title }}</td>
                <td>{{ $bank->is_question }}</td>

                <td style="white-space:nowrap;">
                                <a class="btn btn-sm btn-icon-only btn-outline-info" href="{{ route('banks.show',$bank->id) }}"><i class="pe-7s-look btn-icon-wrapper"></i></a>
                                <a class="btn btn-sm btn-icon-only btn-outline-warning" href="{{ route('banks.edit',$bank->id) }}"><i class="pe-7s-pen btn-icon-wrapper"></i></a>
                                {!! Form::open(['method' => 'DELETE','route' => ['banks.destroy', $bank->id],'style'=>'display:inline']) !!}
                                    {{ Form::button('<i class="pe-7s-trash btn-icon-wrapper"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon-only btn-outline-danger'] ) }}
                                {!! Form::close() !!}
                                <a class="btn btn-sm btn-icon-only btn-outline-success" href="{{ route('questions.create',$bank->id) }}"><i class="pe-7s-note2 btn-icon-wrapper"></i></a>
                </td>
            </tr>
            @endforeach
        </tbody>
    </table>
    <p class="text-center text-primary"><small>Campus Virtual</small></p>
@endsection

    @include('banks.questions.modal_create')


@section('js')

@endsection