routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::get('/', function () {
    return view('auth.login');
});


Route::get('/home', 'HomeController@index')->name('home');

Route::get('/u/courses/list/category', 'Participant\ParticipantController@listCategory')->name('participant.course.listCategory');
Route::get('/u/courses/{category}/list', 'Participant\ParticipantController@list')->name('participant.course.list');
Route::get('/u/courses/{classroom}', 'Participant\ParticipantController@detail')->name('participant.course.detail');
Route::get('/u/courses/sayCheese/{classroom}/cheers', 'Participant\ParticipantController@saycheese')->name('participant.course.saycheese');
Route::get('/u/{user}/courses/{classroom?}', 'Participant\ParticipantController@document')->name('participant.course.document');
Route::post('/u/courses/{classroom}/test/{test}/register', 'Participant\ParticipantController@register')->name('participant.test.register');
Route::get('/u/certificates', 'Participant\ParticipantController@certificates')->name('participant.course.certificates');
Route::get('/user/courses/{classroom}/test_user/{test_user?}/note/participant', 'Participant\ParticipantController@note')->name('participant.course.note');
Route::get('/user/courses/{classroom}/note/nofound', 'Participant\ParticipantController@noteNofound')->name('participant.course.note.nofound');
Route::get('/u/courses/{classroom}/test/{test_user}/result', 'Participant\ParticipantController@result')->name('participant.course.results');
Route::get('u/courses/{classroom}/encuesta/{test_user}','Participant\ParticipantController@encuesta')->name('users.encuesta');
Route::get('/u/courses', 'Participant\CourseController@index')->name('participant.course.index');
Route::get('/courses/detail/{classroom}', 'Participant\CourseController@getDetail')->name('course.detail');





Route::get('/u/courses/{classroom}/test/{test}', 'Participant\ParticipantController@test')->name('participant.course.test');

//
Route::get('/certificate', 'User\CertificateController@index')->name('users.certificate');
Route::get('/certificate/{inscription}', 'User\CertificateController@create')->name('users.certificate.inscriptions');

Auth::routes();
Route::post('/register/company', 'Contractor\RegisterController@store')->name('register.company');

Route::resource('participants','ParticipantController');
Route::get('participants/{user}/modify', 'ParticipantController@modify')->name('participants.modify');
Route::get('participants/{user}/profile', 'ParticipantController@profile')->name('participants.profile');
Route::put('participant/{user}', 'ParticipantController@actualize')->name('participants.actualize');
Route::post('participants/import-excel','ParticipantController@import')->name('participants.import');


Route::resource('facilitators','FacilitadorController');
Route::get('facilitators/{user}/modify', 'FacilitadorController@modify')->name('facilitators.modify');
Route::put('facilitator/{user}', 'FacilitadorController@actualize')->name('facilitators.actualize');
Route::resource('companies','CompanyController');


Route::resource('categories','CategoryController');

Route::get('courses/u', 'Courses\ParticipantsController@list')->name('courses.participant.list');
Route::get('courses/{classroom}/u/{user}', 'Courses\ParticipantsController@detail')->name('courses.participant.detail');
Route::get('courses/{classroom}/types/{type}/u', 'Courses\ParticipantsController@list_type')->name('courses.participant.type');
Route::get('courses/{classroom}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');
Route::resource('courses.contents','Courses\CourseContentController');
Route::get('courses/{course}/types/{type}/contents/{content}/u/play', 'Courses\ParticipantsController@play')->name('courses.participant.play');

Route::resource('courses.types','Courses\CourseTypeController');
Route::resource('courses.types.contents','Courses\CourseTypeContentController');
Route::get('courses/contents/{media}/download','Courses\CourseTypeContentController@download_content')->name('contents.download');

//Route::get('courses/contents/{course}', 'Courses\ContentController@index')->name('courses.contents.index');
Route::resource('courses','CourseController');
Route::resource('courses.certificates','Courses\CourseCertificateController');


Route::get('classrooms/{classroom}/test/{key?}','Classroom\TestController@list')->name('classrooms.list');
Route::resource('classrooms.tests','Classroom\TestController');
Route::resource('classrooms','ClassroomController');
Route::get('classrooms/{classroom}/consolidated', 'Classroom\ClassroomConsolidatedController@consolidated')
    ->name('classrooms.Consolidated');
Route::resource('classrooms.meetings','Classroom\MeetingController');
Route::resource('classrooms.assistances','Classroom\ClassroomAssistanceController');
Route::post('classrooms/{classroom}/assistances/register',
    'Classroom\ClassroomAssistanceController@register')
    ->name('classrooms.assistances.register');

//asistances en facilitator

Route::get('bank/{course}','BankController@save')->name('banks.save');
Route::get('banks/{course?}/module{module?}','BankController@list')->name('banks.list');
Route::resource('banks','BankController');
Route::post('banks/import-excel/{course}','BankController@import')->name('banks.import');;



Route::resource('roles','RoleController');
Route::resource('types','TypeController');
Route::resource('certificates','CertificateController');
Route::resource('users','UserController');
Route::get('courses/{classroom}/test/{test}','Course\CourseTestController@test')->name('courses.test');
Route::get('courses/{classroom}/encuesta/{test_user}','Course\CourseTestController@encuesta')->name('tests.encuesta');
Route::post('courses/{classroom}/test/{test}/register','Course\CourseTestController@register')->name('courses.test.register');
Route::get('courses/{classroom}/test/{test_user}/result','Course\CourseTestController@result')->name('courses.test.result');
Route::get('courses/{classroom}/test/{test_user}/detail','Course\CourseTestController@detail')->name('courses.test.detail');
Route::resource('users.testusers','User\TestUserController');


Route::resource('inscriptions','InscriptionController');
Route::post('inscriptions/import-excel','InscriptionController@import')->name('inscriptions.import');
Route::get('inscriptions/{classroom}/register','InscriptionController@register')->name('inscriptions.register');
Route::post('inscriptions/{classroom}','InscriptionController@save')->name('inscriptions.save');
Route::get('inscriptions/{classroom}/detail','InscriptionController@detail')->name('inscriptions.detail');

Route::resource('classrooms.tests','Classroom\TestController');
Route::get('classrooms.tests/{classroom}/list','Classroom\TestController@list')->name('tests.list');
Route::resource('courses.certificates','Courses\CourseCertificateController');

Route::get('modules/{course}','ModuleController@index')->name('modules.index');
route::get('modules/{course}/create','ModuleController@create')->name('modules.create');
Route::get('module/{module?}/courses/{course?}','ModuleController@show')->name('modules.show');
route::get('modules/{module}/edit','ModuleController@edit')->name('modules.edit');
route::post('modules/{course}','ModuleController@store')->name('modules.store');
route::put('modules/{module}','ModuleController@update')->name('modules.update');
Route::delete('modules/{module}','ModuleController@destroy')->name('modules.destroy');

//videos


//Question
Route::resource('forums','ForumController');
Route::get('courses/{classroom}/videos','ClassroomController@updateTimeVideo')->name('video.time');
Route::get('courses/{classroom}/video','ClassroomController@updateTimeCourse')->name('courses.time');
Route::post('u/courses/video/save/{inscription}','ClassroomController@videoSave')->name('video.save');
//has video guia

Route::get('participants/has/videoGuia/{classroom}','ClassroomController@hasVideoGuia')->name('participants.video.guia');

app/Http/Controllers/Classroom/ClassroomAssistanceController.php
<?php

namespace App\Http\Controllers\Classroom;

use App\Assistance;
use App\Classroom;
use App\Http\Controllers\Controller;
use App\Http\Requests\Assistance\ClassroomAssistanceRequest;
use App\Http\Requests\Assistance\CreateAssistanceRequest;
use App\Http\Requests\Assistance\UpdateAssistanceRequest;
use App\Inscription;
use Carbon\Carbon;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ClassroomAssistanceController extends Controller
{
    function __construct() {
        $this->middleware('auth');
    }

    public function index(Classroom $classroom)
    {
        $classroom->loadCount('scheduledParticipants')
            ->load(['scheduledParticipants']);

        return view('participants.assistances.show', compact('classroom'));
    }

    public function create(Classroom $classroom)
    {
        $assistance = new Assistance();
        return view('participants.assistances.create', compact('assistance', 'classroom'));
    }

    public function store(CreateAssistanceRequest $request, Classroom $classroom)
    {
        $fields = $request->validated();
        $fields['classroom_id'] = $classroom->id;
        $fields['assistance_date']=Carbon::parse($fields['assistance_date'])->format('d-m-Y');
        $meeting = Assistance::create($fields);

        $message = 'La reunión fue registrada correctamente';

        return redirect()->route('classrooms.assistances.index', $classroom->id)->with('success', $message);
    }

    public function show(Classroom $classroom, Assistance $assistance)
    {
        $classroom->loadCount('scheduledParticipants')
            ->load(['scheduledParticipants']);
//        $i = Inscription::find(11);
//        dd($i->assistances);
//        dd($classroom->scheduledParticipants->pivot, $i->assistances);
        return view('participants.assistances.show', ['classroom' => $classroom, 'assistance' => $assistance]);
    }

    public function edit(Classroom $classroom, Assistance $assistance)
    {
        return view('participants.assistances.edit', ['classroom' => $classroom, 'assistance' => $assistance]);
    }

    public function update(UpdateAssistanceRequest $request, Classroom $classroom, Assistance $assistance)
    {
        $fields = $request->validated();
        $fields['classroom_id'] = $classroom->id;
        $assistance->update($fields);

        $message = 'La asistencia fue actualizada correctamente';

        return redirect()->route('classrooms.assistances.index', $classroom->id)->with('success', $message);
    }

    public function delete(ClassroomAssistanceRequest $request, Classroom $classroom) {
        $fields = $request->validated();

        $participants_relation = $fields['assistance'];

        foreach ($participants_relation as $inscription_id) {
            $classroom->inscriptions()->where('id',$inscription_id)->update(['assistance'=>'F']);
        }

        return back();
    }

    public function register(ClassroomAssistanceRequest $request, Classroom $classroom) {
        $fields = $request->validated();

        $participants_relation = $fields['assistance'];

        foreach ($participants_relation as $inscription_id) {
            $classroom->inscriptions()->where('id',$inscription_id)->update(['assistance'=>'A']);
        }

        return back();
    }
}

app/Http/Controllers/Classroom/ClassroomConsolidatedController.php
<?php

namespace App\Http\Controllers\Classroom;

use App\Classroom;
use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class ClassroomConsolidatedController extends Controller
{
    function __construct(){
        $this->middleware('auth');
    }

    public function consolidated(Classroom $classroom)
    {

        $classroom->loadCount('scheduledParticipants')
            ->load('scheduledParticipants');

        return view('classrooms.consolidated',compact('classroom'));
    }
}

app/Http/Controllers/ClassroomController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Course;
use App\Classroom;
use App\Test;
use App\Inscription;
use Illuminate\Support\Facades\Auth;
use App\Http\Requests\Classroom\CreateClassroomRequest;
use Exception;
use Illuminate\Http\Request;

class ClassroomController extends Controller
{
    function __construct(){
        $this->middleware('auth');
        $this->middleware('permission:classroom-list')->only('index');
        $this->middleware('permission:classroom-create',['only'=>['create','store']]);
        $this->middleware('permission:classroom-edit',['only'=>['edit','update']]);
        $this->middleware('permission:classroom-delete',['only'=>['destroy']]);
    }

    public function index()
    {
        $user = Auth::user();

        $query = Classroom::query()
        ->with(['course'])
        ->withCount('scheduledParticipants');

        $classrooms = $query
            ->when($user->hasRole('facilitador'), function ($query) use ($user) {
                return $query->where('user_id','=', $user->id);
            })
            ->latest()
            ->get();

        $classrooms_count = count($classrooms);

        return view('classrooms.index',compact('classrooms', 'classrooms_count'));
    }

    public function list_participant(Classroom $classroom)
    {

        $user=Auth::user();
        $classroom=Classroom::with(['course','user'])
        ->orderBy('classrooms.id','asc')
        ->where('classrooms.user_id','=',$user->id)
        ->first();

        $inscriptions=Inscription::with(['classroom','participant'])
        ->join('classrooms','inscriptions.classroom_id','=','classrooms.id')
        ->join('users','users.id','=','inscriptions.user_id')
        ->select(['inscriptions.id','users.name','users.dni'])
        ->where('inscriptions.classroom_id','=',$classroom->id)
        ->get();

        return view('classroom.assistance',compact('inscription'));
        return view('classroom.assistance',compact('classroom'));
    }

    public function create()
    {
        $classroom = new Classroom();
        $facilitators = User::role('facilitador')->active()->get();
        $courses = Course::orderBy('name')->get();

        return view('classrooms.create',compact('classroom','courses','facilitators'));
    }

    public function store(CreateClassroomRequest $request)
    {
        $fields = $request->validated();
        $course = Course::findOrFail($fields['course_id']);
        $fields['name'] = $course->name;
        $fields['hour'] = $course->hour;
        $fields['grade_min'] = $course->grade_min;
        $fields['validity'] = $course->validity;
        $fields['type_validity'] = $course->type_validity;

        $classroom = Classroom::create($fields);

        $message = 'La programación del curso '. $classroom->name .' fue registrada correctamente';
        return redirect()->route('classrooms.index')->with('success', $message);
    }

    public function show($id)
    {
        $tests = Test::Where('classroom_id',$id)->get();
        return view('classrooms.show',compact('tests'));
    }

    public function edit(Classroom $classroom)
    {
        $facilitators = User::role('facilitador')->active()->get();
        $courses = Course::orderBy('name')->get();
        return view('classrooms.edit',compact('classroom','courses','facilitators'));
    }

    public function update(CreateClassroomRequest $request,Classroom $classroom)
    {

        $fields = $request->validated();
        $course = Course::findOrFail($fields['course_id']);
        $fields['name'] = $course->name;
        $fields['hour'] = $course->hour;
        $fields['grade_min'] = $course->grade_min;
        $fields['validity'] = $course->validity;
        $fields['type_validity'] = $course->type_validity;

        $classroom->update($fields);

        $message = 'La Programación del curso "'. $classroom->name .'" fue actualizada correctamente';
        return redirect()->route('classrooms.index')->with('success', $message);
    }

    public function destroy($id)
    {

    }
    public function updateTimeVideo(Request $request, Classroom $classroom ){
        $user = Auth::user();
        if($request->ajax()){
            $inscriptions=Inscription::where(['user_id'=> $user->id, 'classroom_id'=> $classroom->id])
            ->update(['current_time_video'=>$request->seconds]);
        }
    }
    public function updateTimeCourse(Request $request,Classroom $classroom){
        if($request->ajax()){
            $inscriptions=Inscription::where(['classroom_id'=>$classroom->id,'user_id'=>Auth::user()->id])->update(['teme_course_covert'=>$request->seconds,'time_course'=> $request->integer_seconds]);
        }
    }
    public function videoSave(Request $request,$inscription){
        $fields=$request->all();

            $i=Inscription::where('id',$inscription)->firstOrFail();

            $i->addMedia($fields['myFile'])->toMediaCollection('inscriptions');

        return "succes";
    }
    public function hasVideoGuia(Classroom $classroom ){

        return view('participants.video.guia',compact('classroom'));
    }

}

resources/views/classrooms/consolidated.blade.php
@extends('layouts.template')

@section('content')

    @include('layouts.title', array(
                                    'image'         => 'images/icon-seeder/inicio.png',
                                    'icon'         =>'home',
                                    'title'         => 'Inscripcion del curso "'.$classroom->name.'"',
                                    'description'   => '',
                                    'button'           => 'Regresar',
                                    'href'          => 'classrooms.index'))

    @if ($message = Session::get('success'))
        <div class="alert alert-success">
            <p>{{ $message }}</p>
        </div>
    @endif

    @if (count($errors) > 0)
        <div class="alert alert-danger">
            <strong>Whoops!</strong> There were some problems with your input.<br><br>
            <ul>
                @foreach ($errors->all() as $error)
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <div class="main-card mb-3 card">
        <div class="card-header">Lista De Participantes</div>
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <dl>
                        <dt>FECHA Y HORA DE INICIO</dt>
                        <dd>{{ $classroom->start_datetime }}</dd>
                        <dt>FECHA DE FINALIZACION</dt>
                        <dd>{{ $classroom->end_datetime }}</dd>
                        <dt>INSCRITOS</dt>
                        <dd>{{ $classroom->scheduled_participants_count }}</dd>
                        <dt>MODALIDAD</dt>
                        <dd>{{ $classroom->modality }}</dd>
                    </dl>
                </div>
                <div class="col">
                    <dl>
                        <dt>DESCRIPCION</dt>
                        <dd>{{ $classroom->course->description }}</dd>
                    </dl>
                    <dl>
                        <dt>FACILITADOR</dt>
                        <dd>{{ $classroom->facilitator->full_name }}</dd>
                    </dl>
                </div>
            </div>

            <div class="divider"></div>

            <div class="card-title d-flex justify-content-between align-items-center">
                <span class="mr-2 d-flex">
                    hay <span class="badge badge-primary mr-1 ml-1">{{ $classroom->scheduled_participants_count }}
                    </span>{{ Str::plural('participante', $classroom->scheduled_participants_count) }} {{ Str::plural('inscrito', $classroom->scheduled_participants_count) }}
                </span>

            </div>
            <div class="table-responsive">
                <table class="table table-sm table-hover">
                    <thead class="thead-light">
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Dni</th>
                        <th scope="col">Participante</th>
                        <th scope="col">Estado</th>
                        <th scope="col">Acciones</th>
                    </tr>
                    </thead>
                    <tbody>
                    @foreach ($classroom->scheduledParticipants as $participant)
                        <tr>
                            <th scope="row">{{ $loop->iteration }}</th>
                            <td>{{ $participant->dni }}</td>
                            <td>
                                <div class="widget-content p-0">
                                    <div class="widget-content-wrapper">
                                        <div class="widget-content-left flex2">
                                            <div class="widget-heading">{{ $participant->full_name }}</div>
                                            @if($participant->position || $participant->area)
                                                <div class="widget-subheading opacity-7">{{ $participant->position }} {{ $participant->area }}</div>
                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </td>
                            <td>
                                @if($participant->pivot->state == '0')
                                    <div class="badge badge-danger">
                                        <small>Anulado</small>
                                    </div>
                                @endif
                                @if($participant->pivot->state == '1')
                                    <div class="badge badge-success">
                                        <small>Programado</small>
                                    </div>
                                @endif
                                @if($participant->pivot->state == '2')
                                    <div class="badge badge-info">
                                        <small>Reprogramado</small>
                                    </div>
                                @endif
                            </td>
                            <td>
                                <form action="{{ route('inscriptions.destroy', $participant->id) }}" method="post">
                                    @csrf
                                    @method('delete')
                                    <button
                                        {{ $participant->state == 'Anulado' ? 'disabled' : '' }}
                                        type="submit"
                                        class="btn btn-sm btn-outline-danger">
                                        <i class="fa fa-sm fa-trash-alt"></i> Anular
                                    </button>
                                </form>
                            </td>
                        </tr>
                    @endforeach

                </table>

            </div>
        </div>
    </div>

@endsection
@section('js')
    <script>
        $(document).ready(function () {

        });
    </script>
@endsection

resources/views/classrooms/index.blade.php
@extends('layouts.template')

@section('content')
    <div class="app-page-title">
        <div class="page-title-wrapper">
            <div class="page-title-heading">
                <div class="page-title-icon">
                    <i class="pe-7s-home icon-gradient bg-mean-fruit">
                    </i>
                </div>
                <div>Programación
                    <div class="page-title-subheading">Lista
                    </div>
                </div>

            </div>

            <div class="page-title-actions">
                @can('classroom-list')
                    <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#modalParticipants">Asignación masiva</button>
                @endcan
                @can('classroom-create')
                <div class="d-inline-block dropdown">
                    <a href="{{route('classrooms.create')}}" class="btn-shadow btn btn-info">
                        <span class="btn-icon-wrapper pr-1 opacity-8">
                            <i class="fa fa-plus"></i>
                        </span>
                        REGISTRAR PROGRAMACIÓN
                    </a>
                </div>
                @endcan
            </div>

        </div>
    </div>



<div class="row">
    <div class="col-md-12">
        <div class="main-card mb-3 card">
            <div class="card-header">Hay
                <span class="mx-2 badge badge-primary"> {{ $classrooms_count }}</span>
                cursos Programados
            </div>
            <div class="card-body">
                <div class="table-responsive">
                    @include('layouts.message')
                    <table class="align-middle table table-sm table-hover">
                        <thead class="thead-light">
                            <tr>
                                <th scope="col" >COD</th>
                                <th scope="col" >Curso</th>
                                <th scope="col" >Curso En Chino</th>
                                <th scope="col" >Tipo</th>
                                <th scope="col" >Modalidad</th>
                                <th scope="col" >Fecha y Hora</th>
                                <th scope="col" >Fecha de finalización</th>
                                <th scope="col" >Nota minima</th>
                                <th scope="col" >Vacantes</th>
                                <th scope="col" >Inscritos</th>
                                <th scope="col" >Acciones</th>
                            </tr>
                        </thead>
                        <tbody>

                            @foreach ($classrooms as $classroom)
                            <tr>
                                <td>{{ $classroom->id }}</td>
                                <td>{{ $classroom->course->name }}</td>
                                <td>{{ $classroom->name }}</td>
                                <td>{{ $classroom->type }}</td>
                                <td>{{ $classroom->modality }}</td>
                                <td>{{ $classroom->start_datetime }}</td>
                                <td>{{ $classroom->end_datetime }}</td>
                                <td>{{ $classroom->grade_min }}</td>
                                <td>{{ $classroom->vacancies }}</td>
                                <td>{{ $classroom->scheduled_participants_count }}</td>
                                <td style="white-space:nowrap;">
                                @can('meeting-list')
                                    <a class="btn btn-sm btn-icon-only btn-outline-alternate" title="Videconferencia"
                                        href="{{ route('classrooms.meetings.index', $classroom->id) }}">
                                        <i class="pe-7s-video btn-icon-wrapper"></i>
                                    </a>
                                @endcan
                                @can('test-list')
                                    <a class="btn btn-sm btn-icon-only btn-outline-focus" title="Evaluacion"
                                        href="{{ route('classrooms.list', $classroom->id) }}">
                                        <i class="pe-7s-note2 btn-icon-wrapper"></i>
                                    </a>
                                @endcan
                                @can('classroom-show')
                                    <a class="btn btn-sm btn-icon-only btn-outline-info" title="Ver"
                                    href="{{ route('classrooms.show',$classroom->id) }}"><i class="pe-7s-look btn-icon-wrapper"></i></a>
                                @endcan
                                @can('classroom-edit')
                                    <a class="btn btn-sm btn-icon-only btn-outline-warning" title="Editar" href="{{ route('classrooms.edit',$classroom->id) }}"><i class="pe-7s-pen btn-icon-wrapper"></i></a>
                                        {!! Form::open(['method' => 'DELETE','route' => ['classrooms.destroy', $classroom->id],'style'=>'display:inline']) !!}
                                            {{ Form::button('<i class="pe-7s-trash btn-icon-wrapper"></i>', ['type' => 'submit', 'class' => 'btn btn-sm btn-icon-only btn-outline-danger'] ) }}
                                        {!! Form::close() !!}
                                @endcan
                                @can('inscription-mine')
                                    <a class="btn btn-sm btn-icon-only btn-outline-success {{ ($classroom->vacancies == 0) ? 'disabled' : '' }}"
                                        href="{{ route('inscriptions.register',$classroom->id) }}">
                                        <i class="pe-7s-pen btn-icon-wrapper"></i> Inscribir
                                    </a>
                                @endcan
                                @can('classroom-consolidated')
                                    <a class="btn btn-sm btn-outline-success"
                                    href="{{ route('classrooms.Consolidated', $classroom->id) }}">
                                        <i class="pe-7s-note btn-icon-wrapper"></i> Consolidado
                                    </a>
                                @endcan
                                @role('facilitador')
                                    <a class="btn btn-sm btn-outline-primary"
                                    href="{{ route('classrooms.assistances.index', $classroom->id) }}">
                                        <i class="pe-7s-note btn-icon-wrapper"></i> Asistencia
                                    </a>
                                @endrole
                                <div>

                                </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

@section('modal')
    <div class="modal fade"  id="modalParticipants"   role="dialog" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Registro masivo de Inscripciones</h4>

                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
                </div>
                <form action="{{ route('inscriptions.import')}}" enctype="multipart/form-data" method="post" >
                <div class="modal-body">
                        {{ csrf_field() }}
                        <div class="form-group">
                            <label for="file_up">Asignacion Masiva</label>
                            <input id="file_up" name="file_up" type="file" accept=".xlsx">
                            <p class="help-block">Subir archivos con formato .xlsx</p>
                        </div>
                </div>
                <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                <button type="submit" class="btn btn-primary">Save changes</button>
                </div>
                </form>
            </div>
        </div>
    </div>

    @endsection

@section('js')

@endsection